// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'ccf-info'
  | 'citation-number'
  | 'get-ccf-info'
  | 'paper-info-update'
  | 'requesting-citation-single'
  | 'requesting-citations-multiple';
